var namespaceserialbox =
[
    [ "gridtools", null, [
      [ "field_meta_info", "classserialbox_1_1gridtools_1_1field__meta__info.html", "classserialbox_1_1gridtools_1_1field__meta__info" ],
      [ "meta_info_map", "classserialbox_1_1gridtools_1_1meta__info__map.html", "classserialbox_1_1gridtools_1_1meta__info__map" ],
      [ "savepoint", "classserialbox_1_1gridtools_1_1savepoint.html", "classserialbox_1_1gridtools_1_1savepoint" ],
      [ "serializer", "classserialbox_1_1gridtools_1_1serializer.html", "classserialbox_1_1gridtools_1_1serializer" ]
    ] ],
    [ "stella", null, [
      [ "DataFieldInfo", "classserialbox_1_1stella_1_1DataFieldInfo.html", "classserialbox_1_1stella_1_1DataFieldInfo" ],
      [ "IJKBoundary", "classserialbox_1_1stella_1_1IJKBoundary.html", "classserialbox_1_1stella_1_1IJKBoundary" ],
      [ "IJKSize", "classserialbox_1_1stella_1_1IJKSize.html", "classserialbox_1_1stella_1_1IJKSize" ],
      [ "KBoundary", "classserialbox_1_1stella_1_1KBoundary.html", "classserialbox_1_1stella_1_1KBoundary" ],
      [ "MetainfoSet", "classserialbox_1_1stella_1_1MetainfoSet.html", "classserialbox_1_1stella_1_1MetainfoSet" ],
      [ "Savepoint", "classserialbox_1_1stella_1_1Savepoint.html", "classserialbox_1_1stella_1_1Savepoint" ],
      [ "SerializationException", "classserialbox_1_1stella_1_1SerializationException.html", "classserialbox_1_1stella_1_1SerializationException" ],
      [ "Serializer", "classserialbox_1_1stella_1_1Serializer.html", "classserialbox_1_1stella_1_1Serializer" ]
    ] ],
    [ "Archive", "classserialbox_1_1Archive.html", "classserialbox_1_1Archive" ],
    [ "ArchiveFactory", "classserialbox_1_1ArchiveFactory.html", null ],
    [ "ArrayUtil", "structserialbox_1_1ArrayUtil.html", null ],
    [ "BinaryArchive", "classserialbox_1_1BinaryArchive.html", "classserialbox_1_1BinaryArchive" ],
    [ "BinaryBuffer", "classserialbox_1_1BinaryBuffer.html", "classserialbox_1_1BinaryBuffer" ],
    [ "ConstStorageViewIterator", "classserialbox_1_1ConstStorageViewIterator.html", "classserialbox_1_1ConstStorageViewIterator" ],
    [ "Exception", "classserialbox_1_1Exception.html", "classserialbox_1_1Exception" ],
    [ "FieldID", "structserialbox_1_1FieldID.html", "structserialbox_1_1FieldID" ],
    [ "FieldMap", "classserialbox_1_1FieldMap.html", "classserialbox_1_1FieldMap" ],
    [ "FieldMetainfoImpl", "classserialbox_1_1FieldMetainfoImpl.html", "classserialbox_1_1FieldMetainfoImpl" ],
    [ "Hash", "classserialbox_1_1Hash.html", "classserialbox_1_1Hash" ],
    [ "HashFactory", "classserialbox_1_1HashFactory.html", null ],
    [ "IsArray", "structserialbox_1_1IsArray.html", null ],
    [ "IsArray< Array< T > >", "structserialbox_1_1IsArray_3_01Array_3_01T_01_4_01_4.html", null ],
    [ "IsSupported", "structserialbox_1_1IsSupported.html", "structserialbox_1_1IsSupported" ],
    [ "Logging", "classserialbox_1_1Logging.html", null ],
    [ "MakePrimitive", "structserialbox_1_1MakePrimitive.html", "structserialbox_1_1MakePrimitive" ],
    [ "match_cv_qualifier", "classserialbox_1_1match__cv__qualifier.html", "classserialbox_1_1match__cv__qualifier" ],
    [ "MD5", "classserialbox_1_1MD5.html", "classserialbox_1_1MD5" ],
    [ "MetainfoMapImpl", "classserialbox_1_1MetainfoMapImpl.html", "classserialbox_1_1MetainfoMapImpl" ],
    [ "MetainfoValueImpl", "classserialbox_1_1MetainfoValueImpl.html", "classserialbox_1_1MetainfoValueImpl" ],
    [ "MockArchive", "classserialbox_1_1MockArchive.html", "classserialbox_1_1MockArchive" ],
    [ "NetCDFArchive", "classserialbox_1_1NetCDFArchive.html", "classserialbox_1_1NetCDFArchive" ],
    [ "SavepointImpl", "classserialbox_1_1SavepointImpl.html", "classserialbox_1_1SavepointImpl" ],
    [ "SavepointVector", "classserialbox_1_1SavepointVector.html", "classserialbox_1_1SavepointVector" ],
    [ "SerializerImpl", "classserialbox_1_1SerializerImpl.html", "classserialbox_1_1SerializerImpl" ],
    [ "SHA256", "classserialbox_1_1SHA256.html", "classserialbox_1_1SHA256" ],
    [ "Slice", "classserialbox_1_1Slice.html", "classserialbox_1_1Slice" ],
    [ "SliceTriple", "structserialbox_1_1SliceTriple.html", "structserialbox_1_1SliceTriple" ],
    [ "StorageView", "classserialbox_1_1StorageView.html", "classserialbox_1_1StorageView" ],
    [ "StorageViewIterator", "classserialbox_1_1StorageViewIterator.html", "classserialbox_1_1StorageViewIterator" ],
    [ "StorageViewIteratorBase", "classserialbox_1_1StorageViewIteratorBase.html", "classserialbox_1_1StorageViewIteratorBase" ],
    [ "Timer", "classserialbox_1_1Timer.html", "classserialbox_1_1Timer" ],
    [ "ToType", "structserialbox_1_1ToType.html", null ],
    [ "ToType< TypeID::ArrayOfBoolean >", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfBoolean_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfBoolean_01_4" ],
    [ "ToType< TypeID::ArrayOfFloat32 >", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfFloat32_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfFloat32_01_4" ],
    [ "ToType< TypeID::ArrayOfFloat64 >", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfFloat64_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfFloat64_01_4" ],
    [ "ToType< TypeID::ArrayOfInt32 >", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfInt32_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfInt32_01_4" ],
    [ "ToType< TypeID::ArrayOfInt64 >", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfInt64_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfInt64_01_4" ],
    [ "ToType< TypeID::ArrayOfString >", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfString_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1ArrayOfString_01_4" ],
    [ "ToType< TypeID::Boolean >", "structserialbox_1_1ToType_3_01TypeID_1_1Boolean_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1Boolean_01_4" ],
    [ "ToType< TypeID::Float32 >", "structserialbox_1_1ToType_3_01TypeID_1_1Float32_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1Float32_01_4" ],
    [ "ToType< TypeID::Float64 >", "structserialbox_1_1ToType_3_01TypeID_1_1Float64_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1Float64_01_4" ],
    [ "ToType< TypeID::Int32 >", "structserialbox_1_1ToType_3_01TypeID_1_1Int32_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1Int32_01_4" ],
    [ "ToType< TypeID::Int64 >", "structserialbox_1_1ToType_3_01TypeID_1_1Int64_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1Int64_01_4" ],
    [ "ToType< TypeID::String >", "structserialbox_1_1ToType_3_01TypeID_1_1String_01_4.html", "structserialbox_1_1ToType_3_01TypeID_1_1String_01_4" ],
    [ "ToTypeID", "structserialbox_1_1ToTypeID.html", null ],
    [ "ToTypeID< Array< bool > >", "structserialbox_1_1ToTypeID_3_01Array_3_01bool_01_4_01_4.html", null ],
    [ "ToTypeID< Array< double > >", "structserialbox_1_1ToTypeID_3_01Array_3_01double_01_4_01_4.html", null ],
    [ "ToTypeID< Array< float > >", "structserialbox_1_1ToTypeID_3_01Array_3_01float_01_4_01_4.html", null ],
    [ "ToTypeID< bool >", "structserialbox_1_1ToTypeID_3_01bool_01_4.html", null ],
    [ "ToTypeID< double >", "structserialbox_1_1ToTypeID_3_01double_01_4.html", null ],
    [ "ToTypeID< float >", "structserialbox_1_1ToTypeID_3_01float_01_4.html", null ],
    [ "TypeUtil", "structserialbox_1_1TypeUtil.html", null ],
    [ "Version", "structserialbox_1_1Version.html", "structserialbox_1_1Version" ]
];