name: pip package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-python:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: install boost on macos
        if: ${{ matrix.os  == 'macos-latest'}}
        run: |
          brew install boost
      - name: install boost for ubuntu
        if: ${{ matrix.os   == 'ubuntu-latest'}}
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: upgrade python tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: install dependencies
        run: pip install -r src/serialbox-python/requirements.txt

      - name: build
        run: pip install src/serialbox-python

      - name: run tests
        run: pytest -v test/serialbox-python/serialbox >> $GITHUB_STEP_SUMMARY
