name: Build

on: [push, pull_request]

jobs:
  build_sdist:
    name: Build Python distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install boost
      run: |
        sudo apt-get update
        sudo apt-get install libboost-dev
    - name: Install pypa/build
      run: |
        python -m pip install build --user
    - name: Build source tarball
      run: |
        cd bindings/python
        python -m build --sdist --outdir dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: ./bindings/python/dist/**

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # intel
          - macos-14 # apple silicon
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_SKIP: pp* *musllinux*
          CIBW_BEFORE_BUILD_LINUX: yum -y install boost-devel
          CIBW_BEFORE_BUILD_MACOS: brew install boost # should be ok as we only use headers
        with:
          package-dir: src/serialbox-python
          output-dir: dist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl
